### ISSUE TITLE
Networking error in leader election endpoint

### ISSUE THREAD

**Issue by lucferbux** [openshift/leader-elector#23]
## Description

We are implementing a leader election strategy for a High Availability service. We are using the `ose-leader-elector-rhel8:v4.7` as the base image for the sidecar container, here you have the hole implementation:

```yaml
-   name: jupyterhub-ha-sidecar
    image: 'registry.redhat.io/openshift4/ose-leader-elector-rhel8:v4.7'
    args:
      - '--election=jupyterhub-ha-election'
      - '--election-namespace=$(NAMESPACE)'
      - '--http=0.0.0.0:4040'
      - '--id=$(POD_NAME)'
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
```

The current implementation works great, but given a certain amount of time we bump into the following error in every pod that's running the sidecar container:

```bash
E0907 03:43:50.043988       1 leaderelection.go:253] error retrieving endpoint: Get "https://172.30.0.1:443/api/v1/namespaces/redhat-ods-applications/endpoints/jupyterhub-ha-election": http2: no cached connection was available
```

With this issue, the leader election strategy doesn't work, as the sidecar images don't provide the current name of the leader. Restarting the container fixes the problem.
